### ISSUE TITLE
RecursionError

### ISSUE THREAD

**Issue by pmatra** [patrickchugh/terravision#71]
I'm trying a sample terraform manifest with subdirectories containing local-exec, and a private-key and I get this error.

Unhandled error: <class 'RecursionError'>, maximum recursion depth exceeded in __instancecheck__, <traceback object at 0x7f846389c200>

https://github.com/stacksimplify/terraform-on-aws-ec2.git//08-AWS-ELB-Classic-LoadBalancer/terraform-manifests

Also it would be great if this worked on Gitlab as well as Github without having to make changes to the code.

**Comment by patrickchugh** [comment]
@pmatra Hello, thank you for your feedback and thanks for testing out Terravision and helping to make this a better product. I have recently completed a major revamp to the code which uses the terraform binary to download source files and generate initial relationships, before augmenting it with source code parsing as before. This is a significant departure from the previous approach and whilst slower, ensures a more accurate output and  will handle all terraform in built functions now when encountered in the source.  Please do a git pull and re-test again with the latest source code. If your problem is resolved, please close the the thread in github issues and mark it as completed. If not, please give as much detail as you can about the errors and include any source files if possible so I can reproduce your issue. Once again, thanks for helping and look forward to hearing from you soon.

P.

**Comment by pmatra** [comment]
I am getting this error now after reinstalling the new code and Terraform. I get this on multiple manifests of Terraform. Even the examples.

https://github.com/stacksimplify/terraform-on-aws-ec2.git//08-AWS-ELB-Classic-LoadBalancer/terraform-manifests

Also https://github.com/stacksimplify/terraform-on-aws-ec2.git//09-AWS-ALB-Application-LoadBalancer-Basic/terraform-manifests produces the same error

The K8 example on the github site produces this error too.

```

Traceback (most recent call last):
  File "/home/petermatra/terravision/terravision", line 7, in <module>
    import modules.drawing as drawing
  File "/home/petermatra/terravision/modules/drawing.py", line 9, in <module>
    import modules.helpers as helpers
  File "/home/petermatra/terravision/modules/helpers.py", line 8, in <module>
    from numpy import isin
ModuleNotFoundError: No module named 'numpy'
```

**Comment by patrickchugh** [comment]
@pmatra Can you try again with the latest code?

**Comment by pmatra** [comment]
Using the same URLS I get this error

```
Traceback (most recent call last):
  File "/home/petermatra/terravision/terravision", line 9, in <module>
    import modules.graphmaker as graphmaker
  File "/home/petermatra/terravision/modules/graphmaker.py", line 7, in <module>
    import modules.resource_handlers as resource_handlers
  File "/home/petermatra/terravision/modules/resource_handlers.py", line 1, in <module>
    from debugpy import connect
ModuleNotFoundError: No module named 'debugpy'
```

**Comment by patrickchugh** [comment]
Looks like you are missing the debugpy python module. Type `pip install debugpy`

**Comment by pmatra** [comment]
My first tests were done with WSL Ubuntu 22. Now I switched to a full install of Ubuntu 22 on my server. I'm getting these kind of errors while testing out manifests.

`Unhandled error: <class 'KeyError'>, 'original_count', <traceback object at 0x7ff670b19a80>`

**Comment by patrickchugh** [comment]
@pmatra can you try to do a git pull with the latest code and see if this is fixed? I am able to run it on my machine now with your source link

**Comment by pmatra** [comment]
It looks good, It worked on my two of my tests that was a simple VPC with EC2 instances and also a load balancer!

When I tested this URL with EKS and Cloudwatch Iogs I got an error: terravision draw --source  https://github.com/stacksimplify/terraform-on-aws-eks.git//08-AWS-EKS-Cluster-Basics/01-ekscluster-terraform-manifests

**Comment by patrickchugh** [comment]
@pmatra I tested it with the EKS link and it works with the latest code now
