### ISSUE TITLE
AWS Internet Gateway not supported

### ISSUE THREAD

**Issue by colbyshores** [patrickchugh/terravision#72]
I believe that the internet gateway is not supported as I am receiving the following error:
Unhandled error: <class 'KeyError'>, 'aws_internet_gateway.igw', <traceback object at 0x7f43cbb76d40>

Is that the case and if so I would like to file a feature/bug report. 
Thank you in advance!

**Comment by urbaned121** [comment]
I have the same issue

**Comment by martinscholz-mediatis** [comment]
Same here

**Comment by patrickchugh** [comment]
@colbyshores @urbaned121 @martinscholz-mediatis  Hello, thank you for your feedback and thanks for testing out Terravision and helping to make this a better product. I have recently completed a major revamp to the code which uses the terraform binary to download source files and generate initial relationships, before augmenting it with source code parsing as before. This is a significant departure from the previous approach and whilst slower, ensures a more accurate output and  will handle all terraform in built functions now when encountered in the source.  Please do a git pull and re-test again with the latest source code. If your problem is resolved, please close the the thread in github issues and mark it as completed. If not, please give as much detail as you can about the errors and include any source files if possible so I can reproduce your issue. Once again, thanks for helping and look forward to hearing from you soon.

P.

**Comment by patrickchugh** [comment]
can this be closed?
